# Based on http://conda.pydata.org/docs/travis.html
language: python
python:
  - "2.7"
notifications:
  email: false
before_install:
  - apt-get install libhdf5-serial-dev netcdf-bin libnetcdf-dev
  - apt-get install numpy matplotlib
  - pip install netcdf4
#optional dependencies
  - pip install pandas  # to-pandas
# cartopy projections ?
# iris?
install:
  - python setup.py install

script: py.test
