sudo: false
language: python
python:
  - "2.7"
  - "3.4"
install: pip install tox-travis
script: tox
addons:
  apt:
    packages:
    - libhdf5-serial-dev 
    - netcdf-bin 
    - libnetcdf-dev
    - python-numpy 
    - python-tox
install:
  - python setup.py install
