language: python
sudo : required
python:
  - "2.7"
notifications:
  email: false
before_install:
  - sudo apt-get install libhdf5-serial-dev netcdf-bin libnetcdf-dev
  - sudo apt-get install python-numpy python-matplotlib
  - pip install netcdf4
#optional dependencies
  # - pip install pandas  # to-pandas
# cartopy projections ?
# iris?
install:
  - python setup.py install

script: py.test
