language: python
sudo : false
addons:
  apt:
    packages:
    - libhdf5-serial-dev 
    - netcdf-bin 
    - libnetcdf-dev
    - python-numpy 
    - python-matplotlib
python:
  - "2.7"
notifications:
  email: false
before_install:
  - pip install pip -U
  - pip install netcdf4
  # - pip install pandas  # optional requirement
# test coverage
  - pip install pytest pytest-cov
  - pip install coveralls
#optional dependencies
  # - pip install pandas  # to-pandas
# cartopy projections ?
# iris?
install:
  - python setup.py install

script: py.test --cov dimarray

after-success: coveralls
